version: '3.9'

services:
  db:
    container_name: rashen-sql
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rashen-db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  java_app:
    container_name: java-app
    image: openjdk:17-jdk-alpine
    volumes:
      - ./DiplomGBProject.jar:/app/DiplomGBProject.jar
    command: ["java", "-jar", "/app/DiplomGBProject.jar"]
    depends_on:
      - db
    ports:
      - "8080:8080"
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rashen95@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
